### ISSUE TITLE
Request: Display the amount of (broken) flows and (broken) variables

### ISSUE THREAD

**Issue by dirkg173** [martijnpoppen/com.athom.flowchecker#8]
Hi Martijn,

is it possible to display the amount of:
- all flows
- broken flows *1
- all variables
- broken variables *1

in an overview?

*1 Broken flows and broken variables are not so much interesting like the amount of flows and variables, because they are already listet. So it will be just the cherry on the top of the cake. 😉

BR
Dirk

**Comment by martijnpoppen** [comment]
Fixed
